# Generated by Django 3.2.7 on 2021-09-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_to', models.CharField(max_length=30)),
                ('message_from', models.CharField(max_length=30)),
                ('message_title', models.CharField(max_length=15)),
                ('message_content', models.CharField(max_length=80)),
            ],
        ),
    ]
