# Generated by Django 3.2.7 on 2021-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_2', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='message_content',
            field=models.TextField(),
        ),
    ]
